objects/Gateway_Detail__c.object
<CustomObject>
    <description>A custom object for storing payment gateways credentials and details in the EzyCharge.</description>
    <fields>
        <fullName>Name__c</fullName>
        <externalId>true</externalId>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Gateway Detail</label>
    <nameField>
        <displayFormat>Gateway-{000}</displayFormat>
        <label>Gateway Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gateway Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Recurring_Payment__c.object
<CustomObject>
    <description>A custom object for storing recurring payment details in the EzyCharge</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date_Established__c</fullName>
        <label>Date Established</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ongoing</fullName>
                    <default>true</default>
                    <label>Ongoing</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gateway_Name__c</fullName>
        <label>Gateway Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gateway_Refund_Id__c</fullName>
        <label>Gateway Refund Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gateway_Schedule_Id__c</fullName>
        <label>Gateway Schedule Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Installment_Period__c</fullName>
        <label>Installment Period</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Fortnightly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Six-monthly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Next_Installment_Date__c</fullName>
        <label>Next Installment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RelatedToId__c</fullName>
        <label>Related To Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Recurring Payment</label>
    <nameField>
        <displayFormat>RD-{0000}</displayFormat>
        <label>Recurring Payment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CancelRecurringPaymentController.cls
public with sharing class CancelRecurringPaymentController {
    
    
    @AuraEnabled
    public static List<Recurring_Payment__c> getRecurringRecord(String recordId){
        return  [Select Id,Name,Duration__c,RelatedToId__c,Status__c,Gateway_Refund_Id__c,Gateway_Name__c,Date_Established__c ,Amount__c, Next_Installment_Date__c,Installment_Period__c,Gateway_Schedule_Id__c  from Recurring_Payment__c where Id=:recordId WITH SECURITY_ENFORCED Limit 1];
    }

    //Method to check if gateway is connected or not.
    @AuraEnabled
    public static Boolean isGatewayConnected(String gatewayName){
        gatewayName = gatewayName.replaceAll(' ','_').toLowerCase();
        List<Gateway_Detail__c> checkGateway = [Select Id from Gateway_Detail__c where Name__c =: gatewayName WITH SECURITY_ENFORCED Limit 1];
        if(checkGateway.size() > 0){
            return true;
        }
        else{
            return false;
        }
    }
    
    @AuraEnabled
    public static String cancelRPEzidebit(List<Recurring_Payment__c> existingRP){
        String returnMsg='';
        try{
            RecurringWrapper wrapper=EzidebitHelper.cancelRecurringPayment(existingRP);
            returnMsg=wrapper.status?wrapper.responseMessage:wrapper.errorResponse;
            UtilGateway.MaintainLog(UTILGateway.PayLogSet_JSON);		
        }catch(Exception e){
            returnMsg=e.getMessage();
        }        
        
        return returnMsg;
    }
    
    @AuraEnabled
    public static String cancelPaywayRP(List<Recurring_Payment__c> existingRP){
        String returnMsg='';
        try{
            returnMsg = PaywayHelper.cancelRecurringPayment(existingRP);            
        }catch(Exception exc){
            returnMsg = MessageHandler.wentWrongCatchMessage;
            EmailHandler.sendExceptionEmail('CancelRecurringPaymentController',exc,null);
        }        
        return returnMsg;
    }

    @AuraEnabled
    public static String cancelNABTransactRP(List<Recurring_Payment__c> existingRP){
        String returnMsg='';
        try{
            returnMsg = NABTransactHelper.cancelRecurringPayment(existingRP);
            
        }catch(Exception exc){
            returnMsg = MessageHandler.wentWrongCatchMessage;
            EmailHandler.sendExceptionEmail('CancelRecurringPaymentController',exc,null);
        }        
        return returnMsg;
    }
    
    @AuraEnabled
    public static String cancelRPSimplify(List<Recurring_Payment__c> existingRP){
        String returnMsg='';
        try{
            RecurringWrapper wrapper=SimplifyHelper.cancelRecurringPayment(existingRP);
            returnMsg=wrapper.status?wrapper.responseMessage:wrapper.errorResponse;
        }catch(Exception e){
            returnMsg=e.getMessage();
        }        
        
        return returnMsg;
    }

    @AuraEnabled
    public static String cancelStripeRP(List<Recurring_Payment__c> existingRP){
        String returnMsg='';
        try{
            returnMsg = StripeHelper.processCancelRP(existingRP);
        }catch(Exception e){
            returnMsg = e.getMessage();
        }        
        return returnMsg;
    }
    
    // Sends an Exception email to support.    
    @AuraEnabled
    public static void sendExceptionEmail(String emailBody){
        EmailHandler.sendEmailTo('Error occurred during the process', emailBody, null, false);
    }
}