objects/Gateway_Detail__c.object
<CustomObject>
    <description>A custom object for storing payment gateways credentials and details in the EzyCharge.</description>
    <fields>
        <fullName>Name__c</fullName>
        <externalId>true</externalId>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Gateway Detail</label>
    <nameField>
        <displayFormat>Gateway-{000}</displayFormat>
        <label>Gateway Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gateway Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Recurring_Payment__c.object
<CustomObject>
    <description>A custom object for storing recurring payment details in the EzyCharge</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date_Established__c</fullName>
        <label>Date Established</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ongoing</fullName>
                    <default>true</default>
                    <label>Ongoing</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gateway_Name__c</fullName>
        <label>Gateway Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gateway_Refund_Id__c</fullName>
        <label>Gateway Refund Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gateway_Schedule_Id__c</fullName>
        <label>Gateway Schedule Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Installment_Period__c</fullName>
        <label>Installment Period</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Fortnightly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Six-monthly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Installment_Date__c</fullName>
        <label>Latest Installment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Installment_Date__c</fullName>
        <label>Next Installment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Refund_Status__c</fullName>
        <label>Refund Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RelatedToId__c</fullName>
        <label>Related To Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secured_Token__c</fullName>
        <label>Secured Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Recurring Payment</label>
    <nameField>
        <displayFormat>RD-{0000}</displayFormat>
        <label>Recurring Payment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Transaction__c.object
<CustomObject>
    <description>A custom object for storing the transaction details in the EzyCharge.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gateway_Name__c</fullName>
        <label>Gateway Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recurring_Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recurring Payment</label>
        <referenceTo>Recurring_Payment__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <label>Transaction Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>First Transaction Failure</fullName>
                </value>
                <value>
                    <fullName>Second Transaction Failure</fullName>
                </value>
                <value>
                    <fullName>Permanent Transaction Failure</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>PENDING</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>Transaction-{0000}</displayFormat>
        <label>SF Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateCardDetailController.cls
public with sharing class UpdateCardDetailController {

    @AuraEnabled
    public static Recurring_Payment__c getRecurringRecord(String recordId){
        try {
            Recurring_Payment__c rp = [Select Gateway_Refund_Id__c,Refund_Status__c,Status__c,Gateway_Name__c,Gateway_Schedule_Id__c from Recurring_Payment__c where Id=:recordId WITH SECURITY_ENFORCED Limit 1];
            return rp;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static boolean geTransactionStatus(String recordId){
        List<Transaction__c> failedTransactions = [Select Id, Name, Transaction_Status__c from Transaction__c where Recurring_Payment__c =: recordId AND (Transaction_Status__c = 'First Transaction Failure' OR Transaction_Status__c = 'Second Transaction Failure' OR Transaction_Status__c = 'Permanent Transaction Failure' OR Transaction_Status__c = 'Failed') WITH SECURITY_ENFORCED order by LastModifiedDate DESC Limit 1];
        if(failedTransactions.size() > 0){
            return true;
        }
        else{
            return false;
        }
    }

    //Method to check if gateway is connected or not.
    @AuraEnabled
    public static Boolean isGatewayConnected(String gatewayName){
        gatewayName = gatewayName.replaceAll(' ','_').toLowerCase();
        List<Gateway_Detail__c> checkGateway = [Select Id from Gateway_Detail__c where Name__c =: gatewayName WITH SECURITY_ENFORCED Limit 1];
        if(checkGateway.size() > 0){
            return true;
        }
        else{
            return false;
        }
    }

    @AuraEnabled
    public static string updateCardDetails(String existingRPId, String requestUrl){
        String returnMsg='';
        Recurring_Payment__c existingRP = [Select Id, Amount__c, Date_Established__c, Duration__c, Gateway_Name__c, Gateway_Schedule_Id__c, Installment_Period__c, Last_Installment_Date__c, Next_Installment_Date__c, RelatedToId__c, Secured_Token__c, Status__c From Recurring_Payment__c Where Id =: existingRPId WITH SECURITY_ENFORCED Limit 1];
        String GatewayName=existingRP.Gateway_Name__c.toLowerCase().replaceAll(' ','_');
        try {
            switch on GatewayName {
                when 'stripe' {                    
                	returnMsg = (StripeManager.isConnected) ? StripeHelper.requestUpdateCardDetailPage(existingRP.Id, requestUrl) : StripeManager.detachedReason;
                }
                when 'payway' {
                	returnMsg = (PaywayManager.isConnected) ? PaywayHelper.requestUpdateCardDetails(existingRP.Id, existingRP.Gateway_Schedule_Id__c, requestUrl) : PaywayManager.detachedReason;
                }
                when 'nab_transact' {
                    returnMsg = (NABTransactManager.isConnected)?NABTransactHelper.requestUpdateCardDetails(existingRP.Id, requestUrl):NABTransactManager.detachedReason;
                }
                when 'ezidebit' {
                    returnMsg=(EzidebitManager.isConnected)?EzidebitHelper.requestUpdateCardDetailPage(existingRP.Id,existingRP.Gateway_Schedule_Id__c,requestUrl):EzidebitManager.detachedReason;
                }
                when 'bpoint' {
                    //bpoint update card detail method
                }
                when 'simplify' {
                    returnMsg=(SimplifyManager.isConnected)?SimplifyHelper.requestUpdateCardDetailPage(existingRP.Id, existingRP.Gateway_Schedule_Id__c, requestUrl):SimplifyManager.detachedReason;
                }
                when else{
                    throw new GatewayException('Something went wrong. Please try again.');
                }

            }
        } catch (Exception e) {
            returnMsg=e.getMessage();
        }
        return returnMsg;
    }

    // Sends an Exception email to support.    
    @AuraEnabled
    public static void sendExceptionEmail(String emailBody){
        EmailHandler.sendEmailTo('Error occurred during the process', emailBody, null, false);
    }
}