objects/Gateway_Detail__c.object
<CustomObject>
    <description>A custom object for storing payment gateways credentials and details in the EzyCharge.</description>
    <fields>
        <fullName>Name__c</fullName>
        <externalId>true</externalId>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Gateway Detail</label>
    <nameField>
        <displayFormat>Gateway-{000}</displayFormat>
        <label>Gateway Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gateway Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_GeneralMethodsFromCommonClasses.cls
@isTest
public with sharing class Test_GeneralMethodsFromCommonClasses {
    
    @isTest static void testActivePaymentList(){
        Gateway_Detail__c gateway = TestDataFactory.createValidNABCredentials();
        Gateway_Detail__c gateway1 = TestDataFactory.createValidPaywayCredentials();
        Gateway_Detail__c gateway2 = TestDataFactory.createValidEzidebitCredentials();
        Gateway_Detail__c gateway3 = TestDataFactory.createValidStripeCredentials();
        Gateway_Detail__c gateway4 = TestDataFactory.createValidSimplifyCredentials();
        Test.startTest();
        NABTransactManager.isConnected=true;
        PaywayManager.isConnected=true;
        EzidebitManager.isConnected=true;
        StripeManager.isConnected=true;
        SimplifyManager.isConnected=true;
        ChargeNowController.ActivePaymentList();
        Test.stopTest();
        System.assertEquals(1, [Select Id, Name from Gateway_Detail__c where Name__c = 'nab_transact'].size()); 
    }

    @isTest static void testInstalmentPeriodList(){
        Gateway_Detail__c gateway = TestDataFactory.createValidNABCredentials();
        Test.startTest();
        NABTransactManager.isConnected=true;
        ChargeNowController.InstalmentPeriodList('nab_transact');
        Test.stopTest();
        System.assertEquals(1, [Select Id, Name from Gateway_Detail__c where Name__c = 'nab_transact'].size()); 
    }

    @isTest static void testisGatewayConnected(){
        Gateway_Detail__c gateway = TestDataFactory.createValidNABCredentials();
        Test.startTest();
        NABTransactManager.isConnected=true;
        CancelRecurringPaymentController.isGatewayConnected('ABC');
        Test.stopTest();
        System.assertEquals(0, [Select Id, Name from Gateway_Detail__c where Name__c = 'ABC'].size()); 
    }
}