objects/Payment_Log__c.object
<CustomObject>
    <description>A custom object for maintaining a record log of every response by the payment gateway in the EzyCharge.</description>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Charge_Type__c</fullName>
        <label>Charge Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One Time</fullName>
                </value>
                <value>
                    <fullName>Recurring</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gateway_Name__c</fullName>
        <label>Gateway Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processing_Record_Id__c</fullName>
        <label>Processing Record Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requesting_Url__c</fullName>
        <label>Requesting_Url</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Retry_Schedule_URL__c</fullName>
        <label>Retry Schedule URL</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Serialized_Record__c</fullName>
        <label>Serialized Record</label>
        <length>131070</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Transaction_Id__c</fullName>
        <label>Transaction Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <label>Transaction Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Payment Log</label>
    <nameField>
        <displayFormat>Log-{000}</displayFormat>
        <label>Payment Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Recurring_Payment__c.object
<CustomObject>
    <description>A custom object for storing recurring payment details in the EzyCharge</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Card_Last_Updated_On__c</fullName>
        <label>Card Last Updated On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Established__c</fullName>
        <label>Date Established</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gateway_Name__c</fullName>
        <label>Gateway Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Installment_Period__c</fullName>
        <label>Installment Period</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Fortnightly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Six-monthly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Next_Installment_Date__c</fullName>
        <label>Next Installment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Secured_Token__c</fullName>
        <label>Secured Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Recurring Payment</label>
    <nameField>
        <displayFormat>RD-{0000}</displayFormat>
        <label>Recurring Payment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Transaction__c.object
<CustomObject>
    <description>A custom object for storing the transaction details in the EzyCharge.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gateway_Name__c</fullName>
        <label>Gateway Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recurring_Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recurring Payment</label>
        <referenceTo>Recurring_Payment__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Id__c</fullName>
        <externalId>true</externalId>
        <label>Transaction Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <label>Transaction Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>First Transaction Failure</fullName>
                </value>
                <value>
                    <fullName>Second Transaction Failure</fullName>
                </value>
                <value>
                    <fullName>Permanent Transaction Failure</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>PENDING</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>Transaction-{0000}</displayFormat>
        <label>SF Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Recurring</fullName>
        <active>true</active>
        <description>Transaction record for recurring payments.</description>
        <label>Recurring</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PostUpdateCardDetailsController.cls
public with sharing class PostUpdateCardDetailsController {
    
    public static String tokenValue{get;set;}
    public static String renderMessage{get;set;}
    public String refreshPage{get;set;}
    public String logId{get;set;}
    public String responseText{get;set;}
    public Payment_Log__c logRefId;
    public String gatewayName;
    public String recurringId{get;set;}
    public String result{get;set;}
    public String returnMsg{get;set;}
    public String validationResult;
    public String refundTransactionId;
    public String paymentReference;
    public String cardNumber;
    public String cardExpiry;
    public String cardHolder;
    
    public PostUpdateCardDetailsController(){
        try{
            logId = ApexPages.currentPage().getParameters().get('reference').escapeHtml4();
            responseText = ApexPages.currentPage().getParameters().get('strestext').escapeHtml4();
            tokenValue = ApexPages.currentPage().getParameters().get('token').escapeHtml4();
            paymentReference = ApexPages.currentPage().getParameters().get('refid').escapeHtml4();
            cardNumber = ApexPages.currentPage().getParameters().get('pan').escapeHtml4();
            cardExpiry = ApexPages.currentPage().getParameters().get('expirydate').escapeHtml4(); 
            cardHolder = ApexPages.currentPage().getParameters().get('nameOnCard').escapeHtml4();
            if(logId == 'null'){
                renderMessage = MessageHandler.wentWrongCatchMessage;
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,renderMessage));
            }
            logRefId = [Select Id,Processing_Record_Id__c,Transaction_Id__c,Requesting_Url__c, Retry_Schedule_URL__c, Gateway_Name__c from Payment_Log__c where Id =: logId WITH SECURITY_ENFORCED Limit 1];
            gatewayName = logRefId.Gateway_Name__c;
            recurringId = logRefId.Processing_Record_Id__c;
            if(logRefId.Requesting_Url__c != null){
                refreshPage = logRefId.Requesting_Url__c;
            }else{
                refreshPage = URL.getSalesforceBaseUrl().toExternalForm().substringAfter('//')+'/'+recurringId;
            }
        }
        catch(Exception ex){
            renderMessage = MessageHandler.urlEdit;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,renderMessage));
            System.debug('Stack Trace '+ex.getStackTraceString()+' Message '+ex.getMessage()+' Line number '+ex.getLineNumber());
            EmailHandler.sendExceptionEmail('UpdateCreditCardController', ex, false);
        }
    }
    
    /********Method to update the recurring payment*********/
    public void updateRecurringPayment(){
        try{
            String returnValue = '';
            Date next_installment_date;
            Recurring_Payment__c current_RP = [Select Id, Name, Card_Last_Updated_On__c, Secured_Token__c, Date_Established__c, Installment_Period__c, Next_Installment_Date__c, Amount__c From Recurring_Payment__c Where Id =: recurringId WITH SECURITY_ENFORCED LIMIT 1];
            if(responseText == 'Successful'){
                String token = Apexpages.currentPage().getParameters().get('tokenValue').escapeHtml4();
                Transaction__c check_if_failed_transaction = [Select Id, Name, Transaction_Status__c, Amount__c from Transaction__c Where Recurring_Payment__c =: current_RP.Id WITH SECURITY_ENFORCED ORDER BY LastModifiedDate DESC LIMIT 1];
                
                if(check_if_failed_transaction.Transaction_Status__c == 'Failed' || check_if_failed_transaction.Transaction_Status__c == 'First Transaction Failure' || check_if_failed_transaction.Transaction_Status__c == 'Second Transaction Failure' || check_if_failed_transaction.Transaction_Status__c == 'Permanent Transaction Failure'){
                    RecurringWrapper recurWrap = new RecurringWrapper();
                    recurWrap.sfProcessingId = current_RP.Id;
                    recurWrap.amount = current_RP.Amount__c;
                    recurWrap.instalPeriod = current_RP.Installment_Period__c;
                    recurWrap.startDate = current_RP.Next_Installment_Date__c;
                    recurWrap.tokenValue = current_RP.Secured_Token__c;
                    
                    TransactionWrapper tranWrapper = new TransactionWrapper();
                    tranWrapper.sfProcessingId = check_if_failed_transaction.Id;
                    tranWrapper.amount = current_RP.Amount__c;
                    tranWrapper.transactionDate = current_RP.Next_Installment_Date__c;
                    tranWrapper.recurringRecordId = current_RP.Id;
                    
                    returnValue = NABTransactHelper.updateTransactionBatchProcess(false, true, token, tranWrapper, recurWrap);
                    next_installment_date = Date.valueOf(returnValue.SubStringAfter('&NextInstallmentDate='));
                    returnValue = returnValue.substringBefore('&NextInstallmentDate=');
                    if(returnValue == 'Transaction Successful.'){
                        validationResult = 'Normal';
                    }
                    else{
                        validationResult = returnValue;
                    }
                }
                else{
                    TransactionWrapper transWrapper = new TransactionWrapper();
                    transWrapper.tokenValue = token; 
                    transWrapper.transactionId = paymentReference;
                    transWrapper = NABTransactManager.validateCreditCard(transWrapper);
                    validationResult = transWrapper.transResponse;
                    refundTransactionId = validationResult.SubStringAfter('&TransactionId=');        
                    validationResult = validationResult.substringBefore('&TransactionId=');
                    String response = NABTransactHelper.updateRPForRefundInfo(refundTransactionId,paymentReference, current_RP.Id);
                }
                
                
                if(validationResult == 'Normal'){
                    RecurringWrapper recurWrap = new RecurringWrapper();
                    recurWrap.cardExpiryDate = cardExpiry;
                    recurWrap.cardNumber = cardNumber;
                    recurWrap.cardHolderName = cardHolder;
                    recurWrap.tokenValue = token;
                    recurWrap.sfProcessingId = current_RP.Id;
                    String updateMessage = NABTransactHelper.updateCardDetails(recurWrap);
                    if(updateMessage.contains('successfully') && (check_if_failed_transaction.Transaction_Status__c == 'Failed' || check_if_failed_transaction.Transaction_Status__c == 'First Transaction Failure' || check_if_failed_transaction.Transaction_Status__c == 'Second Transaction Failure' || check_if_failed_transaction.Transaction_Status__c == 'Permanent Transaction Failure')){
                        ReceiptWrapper receiptPageWrap = new ReceiptWrapper();
                        receiptPageWrap.amount = check_if_failed_transaction.Amount__c;
                        receiptPageWrap.paymentResponse = MessageHandler.recurringSuccess;
                        receiptPageWrap.paymentStatus = (validationResult == 'Normal') ? 'Payment Approved' : 'Payment Rejected';
                        receiptPageWrap.establishmentDate = current_RP.Date_Established__c;
                        receiptPageWrap.installPeriod = current_RP.Installment_Period__c;
                        receiptPageWrap.nextInstallmentDate = next_installment_date;
                        receiptPageWrap.chargeType = 'Recurring';
                        String serializedWrapper = JSON.serialize(receiptPageWrap);
                        
                        UTILGateway.PayLogSet_JSON.add(JSON.serialize(new Payment_Log__c(Gateway_Name__c = UTILGateway.NABTRANSWORD,Action__c = UTILGateway.NABTRANSWORD.capitalize() + MessageHandler.chargeFailed, Amount__c = check_if_failed_transaction.Amount__c, Processing_Record_Id__c = current_RP.Id, Charge_Type__c = 'Recurring', Serialized_Record__c = serializedWrapper)));
                        List<Payment_Log__c> new_log = UTILGateway.MaintainLog(UTILGateway.PayLogSet_JSON);
                        Payment_Log__c current_log = new_log.get(new_log.size()-1);
                        returnMsg = '/apex/Q_Charge__GatewayReceiptPage?reference='+current_log.Id;
                    }
                    else{
                        returnMsg = MessageHandler.creditCardUpdatSuccesse+' NAB Transact.';
                    }
                }
                else{
                    RecurringWrapper wrapper = new RecurringWrapper();
                    wrapper.sfProcessingId = current_RP.Id;
                    wrapper.requestUrl = logRefId.Requesting_Url__c;
                    wrapper.responseMessage = validationResult;
                    wrapper = NABTransactHelper.retryUpdateCardDetails(wrapper);            
                    List<Payment_Log__c> paymentLogList = UTILGateway.MaintainLog(UTILGateway.PayLogSet_JSON);
                    Payment_Log__c log = paymentLogList.get(paymentLogList.size()-1);
                    returnMsg = '/apex/Q_Charge__GatewayReceiptPage?reference='+log.Id;
                    
                }
            }
            else if(responseText != null){
                RecurringWrapper wrapper = new RecurringWrapper();
                wrapper.sfProcessingId = current_RP.Id;
                wrapper.requestUrl = logRefId.Requesting_Url__c;
                wrapper.responseMessage = responseText;
                wrapper = NABTransactHelper.retryUpdateCardDetails(wrapper);            
                List<Payment_Log__c> paymentLogList = UTILGateway.MaintainLog(UTILGateway.PayLogSet_JSON);
                Payment_Log__c log = paymentLogList.get(paymentLogList.size()-1);
                returnMsg = '/apex/Q_Charge__GatewayReceiptPage?reference='+log.Id;
            }
        }catch(DmlException dex){
            returnMsg=dex.getMessage();
            EmailHandler.sendExceptionEmail('PostUpdateCardDetailsController', dex, false);
        }
        catch(Exception ex){
            System.debug('Stack trace '+ex.getStackTraceString()+' '+ex.getMessage()+' '+ex.getLineNumber());
            returnMsg = ex.getMessage();
            EmailHandler.sendExceptionEmail('PostUpdateCardDetailsController', ex, false);
        }
    }
    
}