objects/Transaction__c.object
<CustomObject>
    <description>A custom object for storing the transaction details in the EzyCharge.</description>
    <fields>
        <fullName>Gateway_Name__c</fullName>
        <label>Gateway Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>Transaction-{0000}</displayFormat>
        <label>SF Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/NABTransatChargeRPTransactionsBatch.cls
@deprecated
global with sharing class NABTransatChargeRPTransactionsBatch implements Database.Batchable<SObject>, Database.Stateful, Database.AllowsCallouts{

    global set<Id> allTransactionIds = new set<Id>();
    global Database.QueryLocator start(Database.BatchableContext bcx){
        return Database.getQueryLocator([Select Id from Transaction__c where Gateway_Name__c = 'nab transact'WITH SECURITY_ENFORCED]);  
    }

    global void execute(Database.BatchableContext bcx, List<Transaction__c> scope){
    }

    global void finish(Database.BatchableContext bcx){
    }
}